#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 社会项目

# Short bio or description (displayed in the header)
description: 开源影响力 git.io/JURni

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:  # /images/apple-touch-icon.png #

barcode: https://i.imgur.com/WebwHj5.png

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: <i class="fa fa-tags" title="分类"></i>
    url: /categories
  - name: <i class="fa fa-comments" title="论坛"></i>
    url: https://be4.herokuapp.com/
  - name: <i class="fa fa-info-circle" title="关于"></i>
    url: /about

# Pagination
paginate: 50

searchlimit: 100

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: beauti4@protonmail.com
  facebook:
  flickr:
  github: NodeBE4/impact
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  pinterest:
  rss: atom.xml # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: # jekyllrb
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: <a href="https://line-count.herokuapp.com/nodebe4/hero">line_count</a> <a href="https://git.io/JUt9v">短鏈接</a> <a href="https://2047.name/qr/https://git.io/JUt9v">二維碼分享此頁</a> Powered by <a href="https://github.com/AWEEKJ/kiko-now">Kiko Now</a> & <a href="https://github.com/gitalk/gitalk">Gitalk</a>, 站务反馈 <a href="https://be4.herokuapp.com">NodeBE4</a>（<span style="color:red">已被墙</span>）

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # damoresclub.disqus.com

intensedebate: #13bdf6c9084970458179741d3a6af6cf


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Enter your Clicky Analytics Web tracking code
clicky_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://nodebe4.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/impact"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
  html_to_native: true

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - vendor
  - LICENSE
  - README*.md
  - CNAME
  - Gemfile
  - nei.st_scraping_records.txt
  - www.chinese-future.org_scraping_records.txt
  - program-think.blogspot.com*
  - debug.sh
  - perform.js
  - package*

feed:
  posts_limit: 100
  tags: true

# gitalk:
#   clientID: be92e004d07a5eb7c6de
#   clientSecret: b15a95e9eb1e24d7a8e21c1ca1d8fa26651ed69c
#   repo: hero-comments
#   owner: NodeBE4
#   admin:
#     - NodeBE4
#     - duty-machine
#     - thphd
# algolia:
#   application_id: XPLK8EODKC
#   index_name:     opinion # You can replace that with whatever name you want
#   search_only_api_key: cb6c839c65948b7fcdd13991ad4a4665
#   files_to_exclude: [README.md, 404.md, README.ko.md]

destination: _site

future: false
